READ_BYTES_ACRONYM = "rb"

WRITE_ACRONYM = "w"

PDF_FILE_EXTENSION = ".pdf"

WORD_DOCX_FILE_EXTENSION = '.docx'

UTF_8_ENCODING = "utf-8"

GRAPHML_FILE_EXTENSION = ".graphml"

TEXT_GENERATION_METHOD_COLUMN_NAME = 'generation_method'

TEXT_GENERATION_OUTPUT_COLUMN_NAME = 'text_generated'